import type { Metadata } from "next";
import { Overpass } from "next/font/google";
import "./globals.css";
import NavBar from "@/components/NavBar";
import Options from "@/components/Options";
import { MusicProvider } from "@/context/MusicContext";

const fuente = Overpass({
  subsets: ["latin"],
  weight: ["400", "500", "700", "800"],
});

export const metadata: Metadata = {
  title: "MusicApp",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="es">
      <body suppressHydrationWarning={true} className={fuente.className}>
        <MusicProvider>
          <main className="mx-4 h-screen">
            <NavBar />
            <div className="flex overflow-hidden">
              <Options />
              {children}
            </div>
          </main>
        </MusicProvider>
      </body>
    </html>
  );
}
